### ISSUE TITLE
Having trouble with German Version

### ISSUE THREAD

**Issue by speedbomb** [tracktwo/xcomsave#1]
Hi,
I'm not sure if here is the right place, but you mentioned that you're interested in some foreign language save files with problems. If I use the windows binary of xcom2json with my save game of the German game version, i get an error:

```
D:\Program Files (x86)\Steam\steamapps\common\XCom-Enemy-Unknown\Binaries>xcom2json.exe save15
Error (0x000632f5): String mismatch: expected length 24 but found 0
```

Version of xcomjson: 1.1
Version of Xcom EW (XComGame.exe): 1.0.0.9040

[Link to save file](http://www.speedbomb.de/uploads/save15.zip)

Kind regards,
speedbomb

**Comment by tracktwo** [comment]
Thanks for the report! I believe I've fixed the issue and uploaded a new windows version 1.2. Let me know if you still have trouble, but I've successfully converted this save to json and back without any diffs.

**Comment by speedbomb** [comment]
Thanks for the fix! Yes it works and generated tons of json code ;-)
I'll try to "decrypt" the values and perhaps i'll make a gui for your tool!

**Comment by tracktwo** [comment]
Glad to hear it! Depending on what language you're using you might find it easier to use the library API to do the read/write for your GUI instead of trying to translate to and from the JSON. I didn't put the .lib or .h up in the binary release but I can provide a dev release with those or you can rebuild it from source. It's a c++ interface right now but I can also provide a flat C interface if that's easier for your language.
