### ISSUE TITLE
Actual steam version  + CZE language = Generated save is not good

### ISSUE THREAD

**Issue by Gallindko** [tracktwo/xcomsave#20]
Hello

When I decompress and compress Save file with no changes., generated save is corrupt - wont load ingame.
I use CZE language (install files included)
[SampleSaves.zip](https://github.com/tracktwo/xcomsave/files/5455341/SampleSaves.zip)
[xcom_eu_2012_cz_v101.zip](https://github.com/tracktwo/xcomsave/files/5455343/xcom_eu_2012_cz_v101.zip)

**Comment by tracktwo** [comment]
Thanks for the report. Looks like it's not the language that's the problem here, but the version. The EU support was contributed by someone else and I haven't tested it myself. It looks like there is a bug in save regeneration specific to EU.

Can you try the attached version and see if that works for you? This passes my usual test for saves (convert save to json, json back to save2, convert save2 to json2, compare json and json2 to be identical) but I haven't tried it in-game.

If this works I'll make a new release with these changes.

[Debug_xcomsave.zip](https://github.com/tracktwo/xcomsave/files/5458737/Debug_xcomsave.zip)

**Comment by Gallindko** [comment]
Thx, for response.

I cannot run files.
I dont have VS 2015 installed, and cannot install it on my computer, (I have VS code here).
I downloaded dlls with d suffix but stil it ends with error:

![msvcp140d](https://user-images.githubusercontent.com/73620222/97632475-d8a04080-1a32-11eb-969b-e03897d75ba0.png)

Also xcom2json.exe ask me to have appcrt140d.dll + dektopcrt140d.dll, but those are mixed in ucrtbased.dll nowadays...

 :-(

**Comment by tracktwo** [comment]
Here's a release build with the changes, it should have the same dependency list as the latest actual release.

[xcomsave.zip](https://github.com/tracktwo/xcomsave/files/5461729/xcomsave.zip)

**Comment by Gallindko** [comment]
Works Great!
Many Thanks :-)
